// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  Expression = 2,
  ExpressionOpen = 3,
  ExpressionInner = 4,
  ExpressionClose = 5,
  Text = 6
