name: Storybook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Build Storybook
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: true

      - name: Build modules
        run: pnpm build

      - name: Build storybook
        run: |
          pnpm lerna run --scope @gorules/jdm-editor build:storybook
          touch packages/jdm-editor/docs/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAT }}
          folder: packages/jdm-editor/docs
          branch: gh-pages
          clean: true
          force: true
